name: GPTownship
main: com.OmniTekMC.GPTownship.Township
version: 0.2
author: Leonardi 
depend: [GriefPrevention, Vault]

permissions:
  GPTownship.*:
    description: Gives access to all Township functions.
    default: op
    children:
      GPTownship.sell: true
      GPTownship.buy: true
      GPTownship.Adminclaim: true
      GPTownship.collect: true
      GPTownship.reload: true
  GPTownship.sell:
    description: Allows player to sell claims and subclaims.
    default: true
  GPTownship.buy:
    description: Allows player to buy claims and lease subclaims.
    default: true
  GPTownship.Adminclaim:
    description: Allows players to sell admin claims
    default: false
  GPTownship.collect:
    description: Allows players to collect daily Upkeep manually (In case scheduled event didn't go through)
    default: false
  GPTownship.leave:
    description: Allows player to end contract on the claim he is currently standing in.
    default: true
  GPTownship.reload:
    description: Allows the player to reload the Township configuration file.
    default: false

commands:
   townshipcollect:
      description: Collect the Upkeep manually
      usage: /townshipcollect
      permission: GPTownship.collect
      permission-message: You don't have permission to do this.
   townshipleave:
      description: End the contract for the claim you are currently standing in
      usage: /townshipleave
      permission: GPTownship.leave
      permission-message: You don't have permission to do this.
   townshipreload:
      description: Reload the configuration file
      usage: /townshipreload
      permission: GPTownship.reload
      permission-message: You don't have permission to do this.